// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://capkgqqdjczooeffeeig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhcGtncXFkamN6b29lZmZlZWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjA4NTAsImV4cCI6MjA2OTA5Njg1MH0.wl8QLQTUt67p7PnZEfgAfyH9JQRPwIlSPSwFSZADGsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});